SELECT	AG.ACCGRPNAME + ' [' + AG.ACCGRPNUM + ']'  AS ACC_PORT_NAME
,		L.COUNTRY
,		L.STATECODE
,		L.COUNTYCODE
,		L.COUNTY
,		R.REGION
,		L.CRESTA
,       F.FLZone
,       FLD.FLZONE as Flood_Zone
,		W.TIER AS WIND_TIER
,		WD.DESCRIPTION AS WIND_DESCRIPTION
,		Z.ZONE AS ATC_ZONE
,		ADDRMATCH
,		AD.DESCRIPTION AS ADDRESS_LEVEL
,		P.Description AS PERIL
,		X.YB_SEQ
,		X.DESCRIPTION AS YB_DESCRIPTION
,		D.DTC_SEQ
,		D.DESCRIPTION AS DTC_DESCRIPTION
,		D2.NOS_SEQ
,		D2.DESCRIPTION AS NOS_DESCRIPTION
,		CASE P.CODE
WHEN 'TO' THEN (SELECT TOR.ROOFGEOM)
WHEN 'WS' THEN (HU.ROOFGEOM)
ELSE 0
END AS GEOM_ID
,		CASE P.CODE
WHEN 'TO' THEN (SELECT DESCRIPTION FROM RMS_ROOFGEOM WHERE RMS_ROOFGEOM.ID = TOR.ROOFGEOM AND RMS_ROOFGEOM.PERIL='TO' AND RMS_ROOFGEOM.CODE_SET_ID = (	SELECT	CODE_SET_ID
                                                                                                                                                           FROM	EXPOSURE_ANALYSIS..RMS_VERSION_CODESET
                                                                                                                                                           WHERE	VERSION	=	(	SELECT DBNUM
                                                                                                                                                                             FROM	[&db&].dbo.rmsver)) )
WHEN 'WS' THEN (SELECT DESCRIPTION FROM RMS_ROOFGEOM WHERE RMS_ROOFGEOM.ID = HU.ROOFGEOM AND RMS_ROOFGEOM.PERIL='HU' AND RMS_ROOFGEOM.CODE_SET_ID = (	SELECT	CODE_SET_ID
                                                                                                                                                          FROM	EXPOSURE_ANALYSIS..RMS_VERSION_CODESET
                                                                                                                                                          WHERE	VERSION	=	(	SELECT DBNUM
                                                                                                                                                                            FROM	[&db&].dbo.rmsver)))
ELSE 'Unknown'
END AS ROOF_GEOMETRY
,		GRP_DESC AS LoB
,		LC.VALUECUR
,		SUM(LC.VALUEAMT)AS VALUEAMT
,		SOURCE = '&db&'
FROM	RMS_PERIL P
LEFT JOIN	[&db&]..LOCCVG LC ON LC.PERIL = P.PERIL_ID
LEFT JOIN	[&db&]..Loc L ON LC.LOCID = L.LOCID

LEFT JOIN	[&db&]..hudet HU ON HU.LOCID = L.LOCID
LEFT JOIN	[&db&]..todet TOR ON TOR.LOCID = L.LOCID
LEFT JOIN	[&db&]..fldet FLD ON FLD.LOCID = L.LOCID

LEFT JOIN	[&db&]..accgrp AG ON L.ACCGRPID = AG.ACCGRPID
LEFT JOIN	[&db&].dbo.portacct a ON ag.ACCGRPID = a.ACCGRPID
LEFT JOIN	[&db&].dbo.portinfo i ON a.PORTINFOID = i.PORTINFOID


LEFT JOIN	EXPOSURE_ANALYSIS..FDY_TIERS W ON L.COUNTRY COLLATE DATABASE_DEFAULT = W.COUNTRY COLLATE DATABASE_DEFAULT
AND			L.STATECODE COLLATE DATABASE_DEFAULT = W.STATECODE COLLATE DATABASE_DEFAULT
AND			L.COUNTYCODE COLLATE DATABASE_DEFAULT = W.COUNTYCODE COLLATE DATABASE_DEFAULT

LEFT JOIN	EXPOSURE_ANALYSIS..REGIONS R ON LC.PERIL = R.PERILID
AND			L.COUNTRY COLLATE DATABASE_DEFAULT = R.COUNTRYCODE COLLATE DATABASE_DEFAULT
AND			L.STATECODE COLLATE DATABASE_DEFAULT = R.STATECODE COLLATE DATABASE_DEFAULT

LEFT JOIN	EXPOSURE_ANALYSIS..FLZONE F ON L.COUNTRY COLLATE DATABASE_DEFAULT = F.COUNTRY COLLATE DATABASE_DEFAULT
AND			L.STATECODE COLLATE DATABASE_DEFAULT = F.STATECODE COLLATE DATABASE_DEFAULT
AND			L.COUNTYCODE COLLATE DATABASE_DEFAULT = F.COUNTYCODE COLLATE DATABASE_DEFAULT

LEFT JOIN	EXPOSURE_ANALYSIS..FDY_TIERS_DESC WD ON TIER = TIER_ID

LEFT JOIN	EXPOSURE_ANALYSIS..RMS_ADDRMATCH AD ON l.ADDRMATCH = AD.ADDRMATCH_ID

LEFT JOIN	(	SELECT	LOCID
            ,		SEQ_ID AS DTC_SEQ
            ,		DESCRIPTION
            FROM	[&db&].dbo.hudet
            ,		EXPOSURE_ANALYSIS..BANDING
            WHERE	BAND_TYPE='D'
            AND		DISTCOAST >= BAND_FROM
            AND		DISTCOAST < BAND_TO) D ON L.LOCID = D.LOCID

LEFT JOIN	(	SELECT	LOCID
            ,		SEQ_ID AS NOS_SEQ
            ,		DESCRIPTION
            FROM	[&db&].dbo.loc
            ,		EXPOSURE_ANALYSIS..BANDING
            WHERE	BAND_TYPE='S'
            AND		NUMSTORIES between BAND_FROM AND BAND_TO) D2 ON L.LOCID = D2.LOCID

LEFT JOIN	(	SELECT	DISTINCT L.LOCID
            ,		C.PERIL
            ,		SEQ_ID AS YB_SEQ
            ,		DESCRIPTION
            FROM	[&db&].dbo.loc L
            INNER JOIN [&db&].dbo.loccvg C ON L.LOCID = C.LOCID
            INNER JOIN EXPOSURE_ANALYSIS..BANDING ON C.PERIL = PERIL_ID
            WHERE	BAND_TYPE='Y'
            AND		YEAR(YEARBUILT) between BAND_FROM AND BAND_TO) X ON L.LOCID = X.LOCID
AND		LC.PERIL = X.PERIL

LEFT JOIN	EXPOSURE_ANALYSIS..ATC_ZONES Z ON	l.COUNTRY COLLATE DATABASE_DEFAULT = Z.COUNTRY COLLATE DATABASE_DEFAULT
AND			L.STATECODE COLLATE DATABASE_DEFAULT = Z.STATECODE COLLATE DATABASE_DEFAULT
AND			L.COUNTYCODE COLLATE DATABASE_DEFAULT = Z.COUNTYCODE COLLATE DATABASE_DEFAULT

LEFT JOIN	(	SELECT	OCCSCHEME
            ,		OCCTYPE
            ,		SUB_GRP
            ,		GRP_DESC
            FROM EXPOSURE_ANALYSIS..OCC_TYPE T
            INNER JOIN EXPOSURE_ANALYSIS..OCC_SUB_GRP S ON T.SUB_GRP = S.CODE
            WHERE CODE_SET_ID	=	(	SELECT	CODE_SET_ID
                                  FROM	EXPOSURE_ANALYSIS..RMS_VERSION_CODESET
                                  WHERE	VERSION	=	(	SELECT DBNUM
                                                    FROM	[&db&].dbo.rmsver))) OG ON
L.OCCSCHEME COLLATE DATABASE_DEFAULT = OG.OCCSCHEME COLLATE DATABASE_DEFAULT
AND		l.OCCTYPE = OG.OCCTYPE
WHERE ACCGRPNUM IN('&account&')

GROUP BY	AG.ACCGRPNAME + ' [' + AG.ACCGRPNUM + ']'
,			L.COUNTRY
,			L.STATECODE
,			L.COUNTYCODE
,			L.COUNTY
,			R.REGION
,			L.CRESTA
,			W.TIER
,			F.FLZone
,     FLD.FLZONE
,			WD.DESCRIPTION
,			Z.ZONE
,			ADDRMATCH
,			AD.DESCRIPTION
,			P.DESCRIPTION
,			X.YB_SEQ
,			X.DESCRIPTION
,			D.DTC_SEQ
,			D.DESCRIPTION
,			D2.NOS_SEQ
,			D2.DESCRIPTION
,			P.Code
,			HU.ROOFGEOM
,			TOR.ROOFGEOM
,			GRP_DESC
,			LC.VALUECUR
