use [fire_model]

INSERT INTO dbo.location (location_code,  location_description,  audit_dtm, audit_credential) VALUES ('AK','Alaska',GETDATE(), 'jmccabe')
INSERT INTO dbo.location (location_code,  location_description,  audit_dtm, audit_credential) VALUES ('AL','Alabama',GETDATE(), 'jmccabe')
INSERT INTO dbo.location (location_code,  location_description,  audit_dtm, audit_credential) VALUES ('AR','Arkansas',GETDATE(), 'jmccabe')
INSERT INTO dbo.location (location_code,  location_description,  audit_dtm, audit_credential) VALUES ('AZ','Arizona',GETDATE(), 'jmccabe')
INSERT INTO dbo.location (location_code,  location_description,  audit_dtm, audit_credential) VALUES ('CA','California',GETDATE(), 'jmccabe')
INSERT INTO dbo.location (location_code,  location_description,  audit_dtm, audit_credential) VALUES ('CO','Colorado',GETDATE(), 'jmccabe')
INSERT INTO dbo.location (location_code,  location_description,  audit_dtm, audit_credential) VALUES ('CT','Connecticut',GETDATE(), 'jmccabe')
INSERT INTO dbo.location (location_code,  location_description,  audit_dtm, audit_credential) VALUES ('DE','Delaware',GETDATE(), 'jmccabe')
INSERT INTO dbo.location (location_code,  location_description,  audit_dtm, audit_credential) VALUES ('FL','Florida',GETDATE(), 'jmccabe')
INSERT INTO dbo.location (location_code,  location_description,  audit_dtm, audit_credential) VALUES ('GA','Georgia',GETDATE(), 'jmccabe')
INSERT INTO dbo.location (location_code,  location_description,  audit_dtm, audit_credential) VALUES ('IA','Iowa',GETDATE(), 'jmccabe')
INSERT INTO dbo.location (location_code,  location_description,  audit_dtm, audit_credential) VALUES ('IL','Illinois',GETDATE(), 'jmccabe')
INSERT INTO dbo.location (location_code,  location_description,  audit_dtm, audit_credential) VALUES ('IN','Indiana',GETDATE(), 'jmccabe')
INSERT INTO dbo.location (location_code,  location_description,  audit_dtm, audit_credential) VALUES ('KS','Kansas',GETDATE(), 'jmccabe')
INSERT INTO dbo.location (location_code,  location_description,  audit_dtm, audit_credential) VALUES ('KY','Kentucky',GETDATE(), 'jmccabe')
INSERT INTO dbo.location (location_code,  location_description,  audit_dtm, audit_credential) VALUES ('MA','Massachusetts',GETDATE(), 'jmccabe')
INSERT INTO dbo.location (location_code,  location_description,  audit_dtm, audit_credential) VALUES ('MD','Maryland',GETDATE(), 'jmccabe')
INSERT INTO dbo.location (location_code,  location_description,  audit_dtm, audit_credential) VALUES ('ME','Maine',GETDATE(), 'jmccabe')
INSERT INTO dbo.location (location_code,  location_description,  audit_dtm, audit_credential) VALUES ('MI','Michigan',GETDATE(), 'jmccabe')
INSERT INTO dbo.location (location_code,  location_description,  audit_dtm, audit_credential) VALUES ('MN','Minnesota',GETDATE(), 'jmccabe')
INSERT INTO dbo.location (location_code,  location_description,  audit_dtm, audit_credential) VALUES ('MO','Missouri',GETDATE(), 'jmccabe')
INSERT INTO dbo.location (location_code,  location_description,  audit_dtm, audit_credential) VALUES ('MT','Montana',GETDATE(), 'jmccabe')
INSERT INTO dbo.location (location_code,  location_description,  audit_dtm, audit_credential) VALUES ('NC','North Carolina',GETDATE(), 'jmccabe')
INSERT INTO dbo.location (location_code,  location_description,  audit_dtm, audit_credential) VALUES ('ND','North Dakota',GETDATE(), 'jmccabe')
INSERT INTO dbo.location (location_code,  location_description,  audit_dtm, audit_credential) VALUES ('NE','Nebraska',GETDATE(), 'jmccabe')
INSERT INTO dbo.location (location_code,  location_description,  audit_dtm, audit_credential) VALUES ('NH','New Hampshire',GETDATE(), 'jmccabe')
INSERT INTO dbo.location (location_code,  location_description,  audit_dtm, audit_credential) VALUES ('NJ','New Jersey',GETDATE(), 'jmccabe')
INSERT INTO dbo.location (location_code,  location_description,  audit_dtm, audit_credential) VALUES ('NM','New Mexico',GETDATE(), 'jmccabe')
INSERT INTO dbo.location (location_code,  location_description,  audit_dtm, audit_credential) VALUES ('NV','Nevada',GETDATE(), 'jmccabe')
INSERT INTO dbo.location (location_code,  location_description,  audit_dtm, audit_credential) VALUES ('NY','New York',GETDATE(), 'jmccabe')
INSERT INTO dbo.location (location_code,  location_description,  audit_dtm, audit_credential) VALUES ('OH','Ohio',GETDATE(), 'jmccabe')
INSERT INTO dbo.location (location_code,  location_description,  audit_dtm, audit_credential) VALUES ('OK','Oklahoma',GETDATE(), 'jmccabe')
INSERT INTO dbo.location (location_code,  location_description,  audit_dtm, audit_credential) VALUES ('OR','Oregon',GETDATE(), 'jmccabe')
INSERT INTO dbo.location (location_code,  location_description,  audit_dtm, audit_credential) VALUES ('PA','Pennsylvania',GETDATE(), 'jmccabe')
INSERT INTO dbo.location (location_code,  location_description,  audit_dtm, audit_credential) VALUES ('RI','Rhode Island',GETDATE(), 'jmccabe')
INSERT INTO dbo.location (location_code,  location_description,  audit_dtm, audit_credential) VALUES ('SC','South Carolina',GETDATE(), 'jmccabe')
INSERT INTO dbo.location (location_code,  location_description,  audit_dtm, audit_credential) VALUES ('SD','South Dakota',GETDATE(), 'jmccabe')
INSERT INTO dbo.location (location_code,  location_description,  audit_dtm, audit_credential) VALUES ('TN','Tennessee',GETDATE(), 'jmccabe')
INSERT INTO dbo.location (location_code,  location_description,  audit_dtm, audit_credential) VALUES ('TX','Texas',GETDATE(), 'jmccabe')
INSERT INTO dbo.location (location_code,  location_description,  audit_dtm, audit_credential) VALUES ('UT','Utah',GETDATE(), 'jmccabe')
INSERT INTO dbo.location (location_code,  location_description,  audit_dtm, audit_credential) VALUES ('VA','Virginia',GETDATE(), 'jmccabe')
INSERT INTO dbo.location (location_code,  location_description,  audit_dtm, audit_credential) VALUES ('VT','Vermont',GETDATE(), 'jmccabe')
INSERT INTO dbo.location (location_code,  location_description,  audit_dtm, audit_credential) VALUES ('WI','Wisconsin',GETDATE(), 'jmccabe')
INSERT INTO dbo.location (location_code,  location_description,  audit_dtm, audit_credential) VALUES ('WV','West Virginia',GETDATE(), 'jmccabe')
INSERT INTO dbo.location (location_code,  location_description,  audit_dtm, audit_credential) VALUES ('WY','Wyoming',GETDATE(), 'jmccabe')
INSERT INTO dbo.location (location_code,  location_description,  audit_dtm, audit_credential) VALUES ('DC','Dist. of Columbia',GETDATE(), 'jmccabe')
INSERT INTO dbo.location (location_code,  location_description,  audit_dtm, audit_credential) VALUES ('HI','Hawaii',GETDATE(), 'jmccabe')
INSERT INTO dbo.location (location_code,  location_description,  audit_dtm, audit_credential) VALUES ('MS','Mississippi',GETDATE(), 'jmccabe')
INSERT INTO dbo.location (location_code,  location_description,  audit_dtm, audit_credential) VALUES ('ID','Idaho',GETDATE(), 'jmccabe')
INSERT INTO dbo.location (location_code,  location_description,  audit_dtm, audit_credential) VALUES ('LA','Louisiana',GETDATE(), 'jmccabe')
INSERT INTO dbo.location (location_code,  location_description,  audit_dtm, audit_credential) VALUES ('WA','Washington',GETDATE(), 'jmccabe')
INSERT INTO dbo.location (location_code,  location_description,  audit_dtm, audit_credential) VALUES ('Average','Average',GETDATE(), 'jmccabe')
